### ISSUE TITLE
There is no simple way to install native connector in UBUNTU GNOME ? No PPA repository or DEB package ?

### ISSUE THREAD

**Issue by ge0rgecz** [nE0sIghT/chrome-gnome-shell#4]
There is no simple way to install native connector in UBUNTU GNOME ? No PPA repository or DEB package ?

**Comment by nE0sIghT** [comment]
I do not know about such repository or some other packaging attempts for Ubuntu

**Comment by nE0sIghT** [comment]
That is fixed in master. Package is available at ne0sight/chrome-gnome-shell PPA.
Also readme updated with install instructions:

```
sudo add-apt-repository ppa:ne0sight/chrome-gnome-shell
sudo apt-get install chrome-gnome-shell
```
