### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by lig** [nE0sIghT/chrome-gnome-shell#6]
On mature distributions such as Ubuntu, Fedora, Debian, Centos etc, it better to mention `/usr/local` prefix for manually compiled software, e.g.

```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_EXTENSION=OFF ../
```

and install command should use `sudo` to operate properly:

```
sudo make install
```

These steps work ok with chrome-gnome-shell.

**Comment by nE0sIghT** [comment]
Done in master
