### ISSUE TITLE
GNOME trademarks legal status

### ISSUE THREAD

**Issue by nE0sIghT** [nE0sIghT/chrome-gnome-shell#7]
14.01.2016
A message was sent to "licensing at gnome.org" with permission request for using:
1. GNOME logo in Chrome extension.
2. "GNOME" word as first word in:
    - project name at github: "GNOME Shell integration for Chrome"
    - extension name at Chrome store: "GNOME Shell integration"

29.01.2016
Ekaterina Gerasimova answered that request will be discussed at the next board meeting.

09.02.2016
[GNOME Board Meeting of February, 2nd, 2016](http://permalink.gmane.org/gmane.comp.gnome.foundation.announce/735)

> - Trademark request: chrome extension - bug 727936 - integration with GNOME Shell
>   - General feeling that we would prefer for the extension to be hosted on git.gnome.org
>   - If they are a third-party we would probably have to sign an agreement where they acknowledge that the
>     trademark is our property
>   - The agreement can protect us in case the logo is used in association with something else, or in case the
>     project contains malicious code
>   - ACTION: Cosimo to draft an agreement and then we can move the vote on the mailing list

**Comment by nE0sIghT** [comment]
23.02.2016
Incoming message from Cosimo Cecchi with offer to move to GNOME infrastructure as official project or mutually sign an trademarks agreement and keep project 3rd party

Outgoing message to Cosimo Cecchi with move to GNOME infrastructure approval

24.02.2016
Sent request for new git repository at GNOME infrastructure

**Comment by winsock** [comment]
@nE0sIghT If you don't mind ping me on github if/when the repo moves so I can update my Arch Linux AUR package as necessary.

**Comment by nE0sIghT** [comment]
@winsock Deal

**Comment by nE0sIghT** [comment]
Project is in process of migration to GNOME infrastructure.
