### ISSUE TITLE
Can't install gnome-shell-extension

### ISSUE THREAD

**Issue by lyerox** [nE0sIghT/chrome-gnome-shell#8]
Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector.

**Comment by nE0sIghT** [comment]
Did you install native connector? Which way did you use?
https://github.com/GNOME/chrome-gnome-shell#installation

**Comment by JemiloII** [comment]
yeah im not quite sure how to install the connector on centos 7 using gnome. There isn't a yum command for it and im not sure where to put the file `gs-chrome-connector.py`

**Comment by nE0sIghT** [comment]
@JemiloII  
1. Install cmake and git:
`yum install cmake git`  
2. Clone repository:
`git clone https://github.com/GNOME/chrome-gnome-shell.git`  
3. Cd in cloned directory
4. Follow [steps for cmake installation](https://github.com/GNOME/chrome-gnome-shell#manual-installation)

**Comment by lyerox** [comment]
@nE0sIghT I am use archlinux , and install the chrome-gnome-shell via Aur

**Comment by nE0sIghT** [comment]
@lyerox run chromium from command line. Go to http://extensions.gnome.org. Post chromium output here

**Comment by JemiloII** [comment]
@nE0sIghT thanks a bunch, it works for me :)

**Comment by nE0sIghT** [comment]
@lyerox reopen with chromium output if you still having a problem
